[build]
  functions = "./functions"
[dev]
  targetPort = 5173
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, HEAD, PUT, POST, OPTIONS"